# Generated by Django 3.1.2 on 2020-11-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='index',
            new_name='number',
        ),
    ]
