# Generated by Django 3.1.2 on 2020-11-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20201102_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week',
            old_name='number',
            new_name='index',
        ),
    ]
