# Generated by Django 3.1.2 on 2020-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20201102_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='passenger',
        ),
        migrations.AddField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female')], max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
