# Generated by Django 3.1.2 on 2020-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_auto_20201119_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_date',
            new_name='flight_ddate',
        ),
        migrations.AddField(
            model_name='ticket',
            name='coupon_discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='coupon_used',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight_adate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight_fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='other_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_fare',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
